// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Data;

#nullable disable

namespace TaskManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedById")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage employees and departments",
                            Title = "Employee Management System"
                        },
                        new
                        {
                            ProjectId = 2,
                            CreatedById = 2,
                            CreatedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "E-Commerce Application",
                            Title = "Online Shopping Portal"
                        });
                });

            modelBuilder.Entity("TaskManagement.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Description = ".NET Programming",
                            DifficultyLevel = 6,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = 2,
                            Description = "Web Development",
                            DifficultyLevel = 7,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 3,
                            Description = "Database",
                            DifficultyLevel = 5,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = 4,
                            Description = "ORM",
                            DifficultyLevel = 7,
                            Name = "Entity Framework"
                        },
                        new
                        {
                            SkillId = 5,
                            Description = "Frontend",
                            DifficultyLevel = 3,
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            SkillId = 6,
                            Description = "Client Side",
                            DifficultyLevel = 5,
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("TaskManagement.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Descripton")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssigneeId = 1,
                            Descripton = "Create login UI.",
                            DueDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Todo",
                            Title = "Design Login Page"
                        },
                        new
                        {
                            TaskId = 2,
                            AssigneeId = 1,
                            Descripton = "Implement JWT authentication.",
                            DueDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Implement Authentication"
                        },
                        new
                        {
                            TaskId = 3,
                            AssigneeId = 1,
                            Descripton = "Test login functionality.",
                            DueDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "Done",
                            Title = "Write Login Tests"
                        },
                        new
                        {
                            TaskId = 4,
                            AssigneeId = 2,
                            Descripton = "Develop employee CRUD module.",
                            DueDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 1,
                            Status = "Todo",
                            Title = "Employee CRUD"
                        },
                        new
                        {
                            TaskId = 5,
                            AssigneeId = 2,
                            Descripton = "Develop department management.",
                            DueDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "InProgress",
                            Title = "Department Module"
                        },
                        new
                        {
                            TaskId = 6,
                            AssigneeId = 2,
                            Descripton = "Generate attendance reports.",
                            DueDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            ProjectId = 1,
                            Status = "Done",
                            Title = "Attendance Report"
                        },
                        new
                        {
                            TaskId = 7,
                            AssigneeId = 3,
                            Descripton = "Develop product catalog.",
                            DueDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 2,
                            Status = "Todo",
                            Title = "Product Catalog"
                        },
                        new
                        {
                            TaskId = 8,
                            AssigneeId = 3,
                            Descripton = "Implement shopping cart.",
                            DueDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            ProjectId = 2,
                            Status = "InProgress",
                            Title = "Shopping Cart"
                        },
                        new
                        {
                            TaskId = 9,
                            AssigneeId = 3,
                            Descripton = "Implement checkout flow.",
                            DueDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            ProjectId = 2,
                            Status = "Done",
                            Title = "Checkout Process"
                        },
                        new
                        {
                            TaskId = 10,
                            AssigneeId = 4,
                            Descripton = "Integrate payment gateway.",
                            DueDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 2,
                            Status = "Todo",
                            Title = "Payment Gateway"
                        },
                        new
                        {
                            TaskId = 11,
                            AssigneeId = 4,
                            Descripton = "Develop order history module.",
                            DueDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            ProjectId = 2,
                            Status = "InProgress",
                            Title = "Order History"
                        },
                        new
                        {
                            TaskId = 12,
                            AssigneeId = 4,
                            Descripton = "Implement inventory management.",
                            DueDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            ProjectId = 2,
                            Status = "Done",
                            Title = "Inventory Module"
                        },
                        new
                        {
                            TaskId = 13,
                            AssigneeId = 5,
                            Descripton = "Perform UI testing.",
                            DueDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProjectId = 2,
                            Status = "Todo",
                            Title = "UI Testing"
                        },
                        new
                        {
                            TaskId = 14,
                            AssigneeId = 5,
                            Descripton = "Fix reported bugs.",
                            DueDate = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            ProjectId = 2,
                            Status = "InProgress",
                            Title = "Bug Fixing"
                        },
                        new
                        {
                            TaskId = 15,
                            AssigneeId = 5,
                            Descripton = "Deploy application to production.",
                            DueDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            ProjectId = 2,
                            Status = "Done",
                            Title = "Final Deployment"
                        });
                });

            modelBuilder.Entity("TaskManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "John Smith",
                            Password = "Password@123",
                            PhoneNumber = "9876543210",
                            Role = "Manager",
                            Salary = 50000m
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1996, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Alice Johnson",
                            Password = "Password@123",
                            PhoneNumber = "9876543211",
                            Role = "Manager",
                            Salary = 45000m
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@example.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Bob Williams",
                            Password = "Password@123",
                            PhoneNumber = "9876543212",
                            Role = "Developer",
                            Salary = 35000m
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma@example.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Emma Davis",
                            Password = "Password@123",
                            PhoneNumber = "9876543213",
                            Role = "Developer",
                            Salary = 38000m
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael@example.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Michael Brown",
                            Password = "Password@123",
                            PhoneNumber = "9876543214",
                            Role = "Tester",
                            Salary = 42000m
                        });
                });

            modelBuilder.Entity("TaskManagement.Models.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExperienceMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsCertified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("UserSkills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateName = "Microsoft C#",
                            ExperienceMonths = 36,
                            IsCertified = true,
                            SkillId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificateName = "EF Core",
                            ExperienceMonths = 24,
                            IsCertified = true,
                            SkillId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CertificateName = "ASP.NET Core",
                            ExperienceMonths = 30,
                            IsCertified = true,
                            SkillId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExperienceMonths = 20,
                            IsCertified = false,
                            SkillId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExperienceMonths = 18,
                            IsCertified = false,
                            SkillId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            ExperienceMonths = 15,
                            IsCertified = false,
                            SkillId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            ExperienceMonths = 12,
                            IsCertified = false,
                            SkillId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            ExperienceMonths = 10,
                            IsCertified = false,
                            SkillId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            ExperienceMonths = 8,
                            IsCertified = false,
                            SkillId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            ExperienceMonths = 14,
                            IsCertified = false,
                            SkillId = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("TaskManagement.Models.Project", b =>
                {
                    b.HasOne("TaskManagement.Models.User", "CreatedBy")
                        .WithOne("Project")
                        .HasForeignKey("TaskManagement.Models.Project", "CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaskManagement.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Models.User", "Assignee")
                        .WithMany("TaskItems")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManagement.Models.Project", "Project")
                        .WithMany("TaskItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagement.Models.UserSkill", b =>
                {
                    b.HasOne("TaskManagement.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Models.Project", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("TaskManagement.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("TaskManagement.Models.User", b =>
                {
                    b.Navigation("Project")
                        .IsRequired();

                    b.Navigation("TaskItems");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
